flags: {}
packages:
- '.'
extra-deps:
- accelerate-cuda-0.15.1.1
- continued-fractions-0.9.1.1
- converge-0.1.0.1
- cuda-0.7.0.0
- exception-mtl-0.4.0.1
- gamma-0.9.0.2
- language-c-quote-0.11.6.2
- mainland-pretty-0.4.1.4
- symbol-0.2.4
resolver: lts-5.9
